name: Main

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
        
      - name: Publish
        # Publish shouldn't be needed unless we need to deploy
        if: github.ref == 'refs/heads/main'
        run: dotnet publish --configuration Main
      - uses: actions/upload-artifact@master
        with:
          name: publish
          path: Source/bin/x64/Main/net6.0/publish
  
  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build
    # Only deploy on main
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/download-artifact@master
        with:
          name: publish
          path: Source/bin/x64/Main/net6.0/publish

      - name: Transfer files
        run: sshpass -p "${{ secrets.PASSWORD }}" scp -o "StrictHostKeyChecking no" -r Source/bin/x64/Main/net6.0/publish ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/MAAL.API

      - name: Replace process
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -t ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop kestrel-MAAL.API.service
          rm -rf /var/www/MAAL.API
          mv ~/MAAL.API /var/www/MAAL.API
          sudo systemctl start kestrel-MAAL.API.service
          EOF
