name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Build
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # Publish
      - name: Publish
        run: dotnet publish --configuration Release
      - name: Deploy
        run: |
          apt install sshpass
          sshpass -p "${{ secrets.PASSWORD }}" scp -r Source/bin/x64/Release/net6.0/publish ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/MAAL.API
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          kill $(ps aux | grep 'MAAL.API.dll' | awk '{print $2}')
          rm -rf /var/www/MAAL.API
          mv ~/MAAL.API /var/www/MAAL.API
          dotnet ./MAAL.API/MAAL.API.dll
