name: Main

on:
  push:
    branches: ["main", "dev"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - name: Production
        if: github.ref_name == 'main'
        run: echo "ENVIRONMENT=Production" >> $GITHUB_ENV
      - name: Development
        if: github.ref_name == 'dev'
        run: echo "ENVIRONMENT=Debug" >> $GITHUB_ENV
      
      - name: Clone
        run: |
          cd ..
          rm -rf MAAL.API
          git clone git@github.com-MAAL.API:LokenSoftware/MAAL.API.git
          cd MAAL.API
          git checkout origin/${{ github.ref_name }}
      
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore --configuration ${{ env.ENVIRONMENT }}
      
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration ${{ env.ENVIRONMENT }}
      
      - name: Publish
        if: github.ref_name == 'main'
        run: dotnet publish --no-build --no-restore --configuration ${{ env.ENVIRONMENT }} --output Output
  
  Deploy:
    runs-on: self-hosted
    needs:
      - Build
    
    if: github.ref_name == 'main'
    
    steps:
      - name: Replace process
        run: |
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop kestrel-MAAL.API.service
          rm -rf /var/www/MAAL.API
          mv Output /var/www/MAAL.API
          sudo systemctl start kestrel-MAAL.API.service
          