name: Main

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: self-hosted
    
    steps:
      - name: Clone
        run: git checkout origin/main
      
      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore --configuration Release
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
  
  Deploy:
    runs-on: self-hosted
    needs:
      - Build
    
    # Only deploy on main
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Publish
        # We have already restored and built in previous job
        run: rm -rf Output && dotnet publish --no-build --no-restore --configuration Release --output Output
      
      - name: Transfer files
        run: scp -r Output ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/MAAL.API
      
      - name: Replace process
        run: |
          ssh -t ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop kestrel-MAAL.API.service
          rm -rf /var/www/MAAL.API
          mv ~/MAAL.API /var/www/MAAL.API
          sudo systemctl start kestrel-MAAL.API.service
          EOF
          