name: Main

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      output1: Source/bin/x64/Release/net6.0/publish

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish --configuration Release
  
  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Dir
        run: dir
      - name: Transfer files
        run: |
          sudo apt-get install sshpass
          sshpass -p "${{ secrets.PASSWORD }}" scp -r Source/bin/x64/Release/net6.0/publish ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/MAAL.API
      - name: Replace process
        run: |
          kill $(ps aux | grep 'MAAL.API.dll' | awk '{print $2}')
          rm -rf /var/www/MAAL.API
          mv ~/MAAL.API /var/www/MAAL.API
          dotnet ./MAAL.API/MAAL.API.dll
